pipeline {
    agent any

    stages {
        stage('Compile') {
            steps {
                sh 'javac my-first-pipeline/Hello_world.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java -cp my-first-pipeline Hello_world'
            }
        }
    }
}
